Another schema is already stored for node
CallStack (from HasCallStack):
  error, called at src/Data/GraphQL/Result/Getter/Internal.hs:94:11 in graphql-client-0.1.0-56eSVdBnMkzJYo9pxki0G:Data.GraphQL.Result.Getter.Internal